apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: securebooks
  namespace: app
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/securebooks
      sourceRef:
        kind: GitRepository
        name: securebooks-app
        namespace: flux-system
      interval: 1m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  rollback:
    recreate: true
    cleanupOnFail: true
  values:
    replicaCount: 2
    image:
      repository: ghcr.io/enginkosure/securebooks
      pullPolicy: IfNotPresent
      tag: main-latest
    service:
      type: ClusterIP
      port: 8000
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
    postgres:
      host: postgres
      port: 5432
      database: securebooks
      userSecret:
        name: securebooks-db
        userKey: POSTGRES_USER
        passwordKey: POSTGRES_PASSWORD
    labels:
      app: securebooks
      version: v1
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: securebooks
            spec:
              template:
                metadata:
                  labels:
                    app: securebooks
                    version: v1
                spec:
                  securityContext:
                    runAsNonRoot: true
                    runAsUser: 1000
                    fsGroup: 1000
