apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: securebooks
  namespace: app
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/securebooks
      sourceRef:
        kind: GitRepository
        name: securebooks-app
        namespace: flux-system
      interval: 1m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  rollback:
    recreate: true
    cleanupOnFail: true
  values:
    replicaCount: 2
    image:
      repository: nginx
      pullPolicy: IfNotPresent
      tag: latest
    service:
      type: ClusterIP
      port: 8000
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
    postgres:
      host: postgres
      port: 5432
      database: securebooks
      userSecret:
        name: securebooks-db
        userKey: POSTGRES_USER
        passwordKey: POSTGRES_PASSWORD
    labels:
      app: securebooks
      version: v1
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: securebooks
            patch: |-
              - op: add
                path: /spec/template/metadata/labels/app
                value: securebooks
              - op: add
                path: /spec/template/metadata/labels/version
                value: v1
              - op: add
                path: /spec/template/spec/securityContext
                value:
                  runAsNonRoot: true
                  runAsUser: 1000
                  fsGroup: 1000
