apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: app
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-app-to-postgres
  namespace: app
spec:
  podSelector:
    matchLabels:
      app: securebooks
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: postgres
      ports:
        - protocol: TCP
          port: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-app-from-istio
  namespace: app
spec:
  podSelector:
    matchLabels:
      app: securebooks
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: istio-system
      ports:
        - protocol: TCP
          port: 8000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
  namespace: app
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
      ports:
        - protocol: UDP
          port: 53
---
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: deny-cross-namespace-egress
spec:
  selector: "!has(allow-cross-namespace)"
  types:
    - Egress
  egress:
    - action: Allow
      destination:
        namespaceSelector:
          matchLabels:
            name: "{{ source_namespace }}"
    - action: Allow
      destination:
        namespaceSelector:
          matchLabels:
            name: kube-system
    - action: Allow
      destination:
        namespaceSelector:
          matchLabels:
            name: kube-public
    - action: Deny
