apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: securebooks-app
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/$GITHUB_USER/securebooks-app.git
  ref:
    branch: main
  secretRef:
    name: flux-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: securebooks-infra
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/$GITHUB_USER/securebooks-infra.git
  ref:
    branch: main
  secretRef:
    name: flux-system
---
apiVersion: v1
kind: Secret
metadata:
  name: flux-system
  namespace: flux-system
type: Opaque
stringData:
  username: git
  password: $GITHUB_TOKEN
